In [1]:
import torch

#1차원 텐서
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [2]:
tensor = torch.tensor([1,2,3,4])

print('original tensor: ', tensor)
print('original tensor size', tensor.shape)

original tensor:  tensor([1, 2, 3, 4])
original tensor size torch.Size([4])


In [3]:
#batch 차원 추가
tensor_unsqueeze = tensor.unsqueeze(dim=0)
print('batch_added tensor: ' ,tensor_unsqueeze)
print('batch_added tensor size: ', tensor_unsqueeze.shape)
#1차원 tensor >> 2차원 tensor
# 첫번째 차원 : 배치크기 (배치크기 : 1)

batch_added tensor:  tensor([[1, 2, 3, 4]])
batch_added tensor size:  torch.Size([1, 4])


In [4]:
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

input_text = '맛있네요'

#입력 텍스트 >> 인코딩(코드화) >> token_id list 변환
input_idx = tokenizer.encode(input_text)
print(input_idx)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

[167, 100, 249, 168, 252, 230, 167, 226, 97, 168, 248, 242]


In [5]:
#token_id list >> tensor 변환

input_tensor = torch.LongTensor(input_idx)
print(input_tensor)
print(input_tensor.shape) # 1차원


tensor([167, 100, 249, 168, 252, 230, 167, 226,  97, 168, 248, 242])
torch.Size([12])


In [6]:
#batch 추가 >> 모델 입력 형태 변환

input_tensor_unsqueeze = input_tensor.unsqueeze(dim=0)
print(input_tensor_unsqueeze)
print(input_tensor_unsqueeze.shape) # 2차원

#입력텐서 [1,12]
#여기서 첫번째 차원 : 배치 크기(여기서는 1(dim=0), 두번째 차원 : sequence 길이 (여기서는 12))

# 특히 transformer 모델 계열에서는 positional encoding(포지셔널-위치 인코딩) 때문에 배치 차원이 필요함

tensor([[167, 100, 249, 168, 252, 230, 167, 226,  97, 168, 248, 242]])
torch.Size([1, 12])
